### ISSUE TITLE
gitment | tennc'blog

### ISSUE THREAD

**Issue by tennc** [tennc/tennc.github.io#2]
https://tennc.github.io/2017/08/22/gitment/

**Comment by fuzzdb** [comment]
博主 怎么弄的 ？？？？~~~

**Comment by tennc** [comment]
参考 文章最后的那个连接，对照修改，发布的每篇文章，都需要作者本人打开初始化gitment，其他人才能使用

**Comment by xuanxiaodeyu** [comment]
你的博客好帅啊，能不能介绍介绍是怎么做的啊

**Comment by tennc** [comment]
@xuanxiaodeyu  hexo + github page 主题采用 [spfk](https://github.com/luuman/hexo-theme-spfk)
